# This is a basic workflow to help you get started with Actions

name: Manual Slack trigger test
on:
  workflow_dispatch:
    inputs:
      flavor:
        required: true
        type: choice
        options:
          - dev
          - staging
          - production

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Post release to Slack
        uses: 8398a7/action-slack@v3
        with:
          status: "custom"
          fields: repo,message,commit,author,action,eventname,ref,workflow,job,took,pullrequest
          custom_payload: |
            {
              text: 'New release deployed',
              attachments: [{
                fallback: 'fallback',
                color: 'good',
                title: 'Release',
                text: '<https://carvcom.sentry.io/releases/[WEB-${{inputs.flavor}}]%201.1.2%20(642)/|[WEB-dev] 1.1.2 (642)>',
                fields: [{
                  title: 'Environment',
                  value: '${{ inputs.flavor }}',
                  short: true
                }]
              }]
            }        
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_DEPLOY }}
          VERSION: "[WEB-${{inputs.flavor}}] ${{ 1.2.3 }} (${{ github.run_number }})"
        if: success()

